# Generated by Django 4.1 on 2022-10-21 07:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
