# Generated by Django 4.1 on 2022-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_crowdfund_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='received',
            field=models.IntegerField(default=0),
        ),
    ]
