# Generated by Django 4.1.2 on 2022-10-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_autentikasi', '0004_alter_profile_telephone_alter_profile_whatsapp'),
        ('crowdfunding', '0005_alter_crowdfund_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfund',
            name='helpers',
            field=models.ManyToManyField(related_name='users', to='fitur_autentikasi.profile'),
        ),
    ]
