# Generated by Django 4.1 on 2022-10-26 11:49

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitur_autentikasi', '0004_alter_profile_telephone_alter_profile_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=False)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barang_bekas.kategori', to_field='jenis')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barang_bekas.lokasi', to_field='nama')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitur_autentikasi.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
