# Generated by Django 4.1 on 2022-10-14 08:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barang_bekas.kategori')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barang_bekas.lokasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
