# Generated by Django 4.1.2 on 2022-12-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_autentikasi', '0004_alter_profile_telephone_alter_profile_whatsapp'),
        ('barang_bekas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.TextField()),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=False)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barang_bekas.kategori', to_field='jenis')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barang_bekas.lokasi', to_field='nama')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitur_autentikasi.profile')),
            ],
        ),
    ]
