# Generated by Django 4.1 on 2022-10-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang_bekas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'ordering': ('-uploaded_at',)},
        ),
        migrations.AddField(
            model_name='barang',
            name='avalaible',
            field=models.BooleanField(default=False),
        ),
    ]
