# Generated by Django 4.1 on 2022-10-15 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang_bekas', '0002_alter_barang_options_barang_avalaible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='lokasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barang_bekas.lokasi', to_field='nama'),
        ),
        migrations.AlterField(
            model_name='lokasi',
            name='nama',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
