# Generated by Django 4.1 on 2022-10-15 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang_bekas', '0003_alter_barang_lokasi_alter_lokasi_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barang_bekas.kategori', to_field='jenis'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='jenis',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
