# Generated by Django 4.1 on 2022-10-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang_bekas', '0004_alter_barang_kategori_alter_kategori_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
