# Generated by Django 4.1 on 2022-10-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang_bekas', '0005_alter_barang_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='avalaible',
            new_name='available',
        ),
    ]
