# Generated by Django 4.1.2 on 2022-10-29 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitur_autentikasi', '0004_alter_profile_telephone_alter_profile_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 10, 30, 1, 35, 53, 428646))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitur_autentikasi.profile', to_field='user')),
            ],
        ),
    ]
