# Generated by Django 4.1.2 on 2022-10-29 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 1, 36, 2, 310167)),
        ),
    ]
