# Generated by Django 4.1.2 on 2022-11-01 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 16, 56, 40, 95218)),
        ),
    ]
