# Generated by Django 4.1.2 on 2022-11-02 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_autentikasi', '0004_alter_profile_telephone_alter_profile_whatsapp'),
        ('information', '0006_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 23, 4, 6, 373137)),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitur_autentikasi.profile'),
            preserve_default=False,
        ),
    ]
