# Generated by Django 4.1.2 on 2022-12-06 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_alter_review_created_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 12, 48, 40, 275864)),
        ),
    ]
