# Generated by Django 4.1.2 on 2022-12-12 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 13, 34, 22, 634098)),
        ),
    ]
