# Generated by Django 4.1 on 2022-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_autentikasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.IntegerField(),
        ),
    ]
